define(function(require) {
  'use strict';

  return [{
    'id': '17',
    'title': 'Activity Stream',
    'titleUrl': null,
    'url': 'https://raw.github.com/OpenSocial/examples/master/gadgets/activitystream/gadget.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'OpenSocial Foundation',
    'authorEmail': null,
    'description': 'OpenSocial Activity Stream gadget with support for Embedded Experiences',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': true
  },
  {
    'id': '30',
    'title': 'Actions Example',
    'titleUrl': null,
    'url': 'http://localhost:8080/demogadgets/actions_contributions.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Rave Project',
    'authorEmail': null,
    'description': 'Actions contributions examples',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '12',
    'title': 'Activity Streams',
    'titleUrl': null,
    'url': 'http://localhost:8080/demogadgets/my_activity.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Anthony Carlucci',
    'authorEmail': null,
    'description': 'Static widget of activities for demoing on the Person Profile page',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '18',
    'title': 'Album Viewer',
    'titleUrl': null,
    'url': 'http://localhost:8080/samplecontainer/examples/embeddedexperiences/AlbumViewer.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Apache Shindig',
    'authorEmail': null,
    'description': 'Sample Embedded Experience gadget from Shindig',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '13',
    'title': 'Current Schedule',
    'titleUrl': null,
    'url': 'http://localhost:8080/demogadgets/schedule.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Anthony Carlucci',
    'authorEmail': null,
    'description': 'Static widget of a schedule for demoing on the Person Profile page',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '28',
    'title': 'EE YouTube Example',
    'titleUrl': null,
    'url': 'http://opensocial2.org:8080/collabapp/pages/home/embeddedExperiences/YouTube.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'OpenSocial Foundation',
    'authorEmail': null,
    'description': 'Example Youtube Embedded Experience Gadget',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '29',
    'title': 'EE jQuery Photo Example',
    'titleUrl': null,
    'url': 'http://accelerator.opensocial2.org/gadgets/photos/jquery_photo_ee.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'OpenSocial Foundation',
    'authorEmail': null,
    'description': 'Example jQuery Photo Embedded Experience Gadget',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '14',
    'title': 'Favorite Websites',
    'titleUrl': null,
    'url': 'http://localhost:8080/demogadgets/favorite_websites.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Anthony Carlucci',
    'authorEmail': null,
    'description': 'Static widget of favorite websites for demoing on the Person Profile page',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '27',
    'title': 'Friends',
    'titleUrl': null,
    'url': 'http://localhost:8080/demogadgets/friends.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Viknes Balasubramanee',
    'authorEmail': null,
    'description': 'This gadget display the list of friends for a particular user',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '10',
    'title': 'Gadget View Type',
    'titleUrl': null,
    'url': 'http://localhost:8080/demogadgets/canvas-nav.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': null,
    'authorEmail': null,
    'description': null,
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '4',
    'title': 'Google News Gadget',
    'titleUrl': null,
    'url': 'http://www.gstatic.com/ig/modules/tabnews/tabnews.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': null,
    'authorEmail': null,
    'description': null,
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '6',
    'title': 'Herbie Hamster Virtual Pet',
    'titleUrl': null,
    'url': 'http://hosting.gmodules.com/ig/gadgets/file/109548057311228444554/hamster.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Naj',
    'authorEmail': null,
    'description': 'A cute little hamster for you to feed and look after. Watch him follow your cursor around. Click on the more tab to treat him to a strawberry. Click him then put him on the wheel and watch him play! ***NEW: make Herbie hamster your very own!',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '7',
    'title': 'List of CTSS Resources - Map View',
    'titleUrl': null,
    'url': 'http://localhost:8080/demogadgets/CTSSResourcesMapView.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Suresh Deivasigamani',
    'authorEmail': null,
    'description': 'This is a gadget developed for Teragrid - OGCE project. Used Google gadgets API to retrieve the information from the Information Services REST Web Service and display the information using Google Maps API. This is a list of available CTSS resources and its details',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '16',
    'title': 'My Experience',
    'titleUrl': null,
    'url': 'http://localhost:8080/demogadgets/my_experience.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Anthony Carlucci',
    'authorEmail': null,
    'description': 'Static widget of experience for demoing on the Person Profile page',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '15',
    'title': 'My Groups',
    'titleUrl': null,
    'url': 'http://localhost:8080/demogadgets/my_groups.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Anthony Carlucci',
    'authorEmail': null,
    'description': 'Static widget of groups for demoing on the Person Profile page',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '3',
    'title': 'NYTimes.com - Top Stories',
    'titleUrl': null,
    'url': 'http://widgets.nytimes.com/packages/html/igoogle/topstories.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': null,
    'authorEmail': null,
    'description': null,
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '20',
    'title': 'OAuth2 Facebook',
    'titleUrl': null,
    'url': 'http://localhost:8080/samplecontainer/examples/oauth2/oauth2_facebook.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Apache Shindig',
    'authorEmail': null,
    'description': 'Sample Facebook gadget from Shindig',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '23',
    'title': 'Ohloh Apache Rave COCOMO Estimates',
    'titleUrl': null,
    'url': 'http://www.ohloh.net/p/521520/widgets/project_cocomo.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Ohloh',
    'authorEmail': null,
    'description': 'Ohloh is an open source network that connects people through the software they create and use. Ohloh gadgets provide detailed statistics about open source software projects and developers.',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '22',
    'title': 'Ohloh Apache Rave Factoids',
    'titleUrl': null,
    'url': 'http://www.ohloh.net/p/521520/widgets/project_factoids.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Ohloh',
    'authorEmail': null,
    'description': 'Ohloh is an open source network that connects people through the software they create and use. Ohloh gadgets provide detailed statistics about open source software projects and developers.',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '21',
    'title': 'Ohloh Apache Rave Languages',
    'titleUrl': null,
    'url': 'http://www.ohloh.net/p/521520/widgets/project_languages.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Ohloh',
    'authorEmail': null,
    'description': 'Ohloh is an open source network that connects people through the software they create and use. Ohloh gadgets provide detailed statistics about open source software projects and developers.',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '24',
    'title': 'Ohloh Apache Rave Stats',
    'titleUrl': null,
    'url': 'http://www.ohloh.net/p/521520/widgets/project_basic_stats.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Ohloh',
    'authorEmail': null,
    'description': 'Ohloh is an open source network that connects people through the software they create and use. Ohloh gadgets provide detailed statistics about open source software projects and developers.',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '9',
    'title': 'Open Views Demo',
    'titleUrl': null,
    'url': 'http://localhost:8080/demogadgets/open_views_demo.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Erin Noe-Payne',
    'authorEmail': null,
    'description': 'A demo gadget to show open views popups in action.',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '25',
    'title': 'OpenAJAX Hub Publisher',
    'titleUrl': null,
    'url': 'http://localhost:8080/container/sample-pubsub-2-publisher.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Apache Shindig',
    'authorEmail': null,
    'description': 'OpenAJAX Hub publisher gadget from Shindig',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '26',
    'title': 'OpenAJAX Hub Subscriber',
    'titleUrl': null,
    'url': 'http://localhost:8080/container/sample-pubsub-2-subscriber.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Apache Shindig',
    'authorEmail': null,
    'description': 'OpenAJAX Hub subscriber gadget from Shindig',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '5',
    'title': 'Pet Hamster',
    'titleUrl': null,
    'url': 'http://hosting.gmodules.com/ig/gadgets/file/112581010116074801021/hamster.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': null,
    'authorEmail': null,
    'description': null,
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '19',
    'title': 'Photo List',
    'titleUrl': null,
    'url': 'http://localhost:8080/samplecontainer/examples/embeddedexperiences/PhotoList.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Apache Shindig',
    'authorEmail': null,
    'description': 'Sample Embedded Experience gadget from Shindig',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '2',
    'title': 'Translate Gadget',
    'titleUrl': 'http://translate.google.com/',
    'url': 'http://www.gstatic.com/ig/modules/dictionary/dictionary.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Google Taiwan',
    'authorEmail': 'googlemodules+dictionary+201109071@google.com',
    'description': 'Google Translation gadget.',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '11',
    'title': 'User Prefs Demo',
    'titleUrl': null,
    'url': 'http://localhost:8080/demogadgets/user_prefs_demo.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'Anthony Carlucci',
    'authorEmail': null,
    'description': 'An example gadget which demos some of the different capabilities of user preferences.',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '1',
    'title': 'Wikipedia',
    'titleUrl': 'http://en.wikipedia.org/wiki/Main_Page',
    'url': 'http://www.widget-dico.com/wikipedia/google/wikipedia.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'WidgetMe',
    'authorEmail': 'google@widgetme.com',
    'description': 'A Wikipedia Search and Go widget. Language choice.',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  },
  {
    'id': '8',
    'title': 'Youtube',
    'titleUrl': null,
    'url': 'http://localhost:8080/demogadgets/youtubesearch.xml',
    'thumbnailUrl': null,
    'screenshotUrl': null,
    'type': 'OpenSocial',
    'author': 'David Olsen',
    'authorEmail': null,
    'description': 'A search module, which searches YouTube by tags like Politics News Life Music Family Photography Art Random Travel Personal Religion Movies Business Thoughts Media Humor Culture Poetry Christmas Writing Books Food Friends.',
    'status': 'PUBLISHED',
    'properties': null,
    'disable': false,
    'disabledMessage': null,
    'featured': false
  }];
});
